# Generated by Django 3.1.2 on 2020-12-31 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturent_uid', models.CharField(default=' ', max_length=20)),
                ('image', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='food')),
            ],
        ),
        migrations.CreateModel(
            name='donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=800)),
                ('des', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default=' ', max_length=20)),
                ('brandname', models.CharField(default=' ', max_length=20)),
                ('price', models.IntegerField(default=0, null=True)),
                ('des', models.CharField(default=' ', max_length=200)),
                ('highlight', models.CharField(default=' ', max_length=500)),
                ('overview', models.CharField(default=' ', max_length=500)),
                ('gst', models.IntegerField(default=0, null=True)),
                ('food_type', models.CharField(default='Veg', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='food_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('des', models.CharField(default=' ', max_length=200)),
                ('image', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='food_category')),
            ],
        ),
        migrations.CreateModel(
            name='promo_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0, null=True)),
                ('des', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='resturent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=20)),
                ('resturent_name', models.CharField(default='', max_length=100)),
                ('mobile', models.CharField(default='9999999999', max_length=20)),
                ('city', models.CharField(default='noida', max_length=50)),
                ('state', models.CharField(default='Delhi', max_length=50)),
                ('zipcode', models.CharField(default='666666', max_length=10)),
                ('address', models.CharField(default='First Name', max_length=400)),
                ('locality', models.CharField(default='', max_length=20)),
                ('average_price', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='resturent')),
                ('image1', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='resturent')),
                ('opening', models.CharField(default='close', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='resturent_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('des', models.CharField(default=' ', max_length=200)),
                ('image', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='resturent_category')),
            ],
        ),
        migrations.CreateModel(
            name='special_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='food')),
                ('name', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='spotlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotId', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=20)),
                ('store_name', models.CharField(default='', max_length=100)),
                ('mobile', models.CharField(default='9999999999', max_length=20)),
                ('city', models.CharField(default='noida', max_length=50)),
                ('state', models.CharField(default='Delhi', max_length=50)),
                ('zipcode', models.CharField(default='666666', max_length=10)),
                ('address', models.CharField(default='address', max_length=400)),
                ('locality', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='store')),
                ('image1', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='store')),
                ('opening', models.CharField(default='close', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='store_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('des', models.CharField(default=' ', max_length=200)),
                ('image', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='store_category')),
            ],
        ),
        migrations.CreateModel(
            name='store_product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('des', models.CharField(default=' ', max_length=200)),
                ('image', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='store_product_category')),
            ],
        ),
        migrations.CreateModel(
            name='store_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default=' ', max_length=20)),
                ('brandname', models.CharField(default=' ', max_length=20)),
                ('price', models.IntegerField(default=0, null=True)),
                ('des', models.CharField(default=' ', max_length=200)),
                ('highlight', models.CharField(default=' ', max_length=500)),
                ('overview', models.CharField(default=' ', max_length=500)),
                ('gst', models.IntegerField(default=0, null=True)),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.store_product_category')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.store')),
            ],
        ),
        migrations.CreateModel(
            name='store_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', django_cryptography.fields.encrypt(models.CharField(default=' ', max_length=100))),
                ('password', django_cryptography.fields.encrypt(models.CharField(default=' ', max_length=100))),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.store')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.store_category'),
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='special_resturent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=160)),
                ('resturent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.resturent')),
            ],
        ),
        migrations.CreateModel(
            name='special_foog_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.food_category')),
                ('special', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.special_category')),
            ],
        ),
        migrations.CreateModel(
            name='special_dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.food')),
            ],
        ),
        migrations.CreateModel(
            name='resturent_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', django_cryptography.fields.encrypt(models.CharField(default=' ', max_length=100))),
                ('password', django_cryptography.fields.encrypt(models.CharField(default=' ', max_length=100))),
                ('resturent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.resturent')),
            ],
        ),
        migrations.AddField(
            model_name='resturent',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.resturent_category'),
        ),
        migrations.AddField(
            model_name='resturent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='rating_for_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('for_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.store')),
            ],
        ),
        migrations.CreateModel(
            name='rating_for_restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=1)),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('for_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.resturent')),
            ],
        ),
        migrations.CreateModel(
            name='product_specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(default=' ', max_length=200)),
                ('des', models.CharField(default=' ', max_length=100)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.store_product')),
            ],
        ),
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='product')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.store_product')),
            ],
        ),
        migrations.CreateModel(
            name='inSpotlight_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.store')),
            ],
        ),
        migrations.CreateModel(
            name='inSpotlight_restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturentK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.resturent')),
            ],
        ),
        migrations.CreateModel(
            name='inspotlight_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.food')),
            ],
        ),
        migrations.CreateModel(
            name='insplotlight_product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.store_product_category')),
            ],
        ),
        migrations.CreateModel(
            name='insplotlight_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.store_product')),
            ],
        ),
        migrations.CreateModel(
            name='insplotlight_food_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.food_category')),
            ],
        ),
        migrations.CreateModel(
            name='food_sub_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(default='cat name', max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('for_food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.food')),
            ],
        ),
        migrations.CreateModel(
            name='food_specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(default=' ', max_length=200)),
                ('des', models.CharField(default=' ', max_length=100)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.food')),
            ],
        ),
        migrations.CreateModel(
            name='food_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='food')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.food')),
            ],
        ),
        migrations.CreateModel(
            name='food_extra_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('for_food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.food')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='food_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.food_category'),
        ),
        migrations.AddField(
            model_name='food',
            name='resturent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.resturent'),
        ),
        migrations.CreateModel(
            name='cms_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=20)),
                ('mobile', models.CharField(default='9999999999', max_length=20)),
                ('city', models.CharField(default='noida', max_length=50)),
                ('state', models.CharField(default='Delhi', max_length=50)),
                ('zipcode', models.CharField(default='666666', max_length=10)),
                ('address', models.CharField(default='xyx', max_length=400)),
                ('image', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='store_category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
