# Generated by Django 3.1.2 on 2021-01-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturent',
            name='locality',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='store',
            name='locality',
            field=models.CharField(default='', max_length=200),
        ),
    ]
