from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('login/',login),
    path("signup/",signup.as_view()),
    path("get_store_category/",get_store_category),
    path("get_product_category/",get_product_category),
    path("get_resturent_category/",get_resturent_category),
    path("get_food_category/",get_food_category),
    path("get_product_by_category/<str:name>/",get_product_by_category),
    path("detail_product_view/<str:uid>/",detail_product_view),
    path("get_food_by_category/<str:name>/",get_food_by_category),
    path("detail_food_view/<str:uid>/",detail_food_view),
    path("store_list/",store_list),
    path("resturent_list/",resturent_list),
    path("resturent_list_in_city/",resturent_list_in_city),
    path("store_list_in_city/",store_list_in_city),
    path("store_products/<str:uid>/",store_products),
    path("resturent_foods/<str:uid>/",resturent_foods),
    path("get_product_by_category_in_city/<str:name>/",get_product_by_category_in_city),
    path("get_food_by_category/",get_food_by_category),
    path("get_food_by_category_in_city/<str:name>/",get_food_by_category_in_city),
    path("add_to_cart",add_to_cart),
    path('get_restaurant_by_cat/<str:catId>', get_restaurant_by_cat),
    path('get_store_by_cat/<str:catId>', get_store_by_cat),
    path('get_all_food', get_all_food),
    path("remove_to_cart/<str:uid>/",remove_to_cart),
    path("all_cart/",all_cart),
    path("update_cart/",update_cart),
    path('get_all_store_product', get_all_store_product),
    path('get_food_extra_items/<str:uid>', get_food_extra_items),
    # path("checkout/",checkout),
    # path("order_placed_same_address/",order_placed_same_address),
    path("previous_order_complete/",previous_order_complete),
    path("previous_order_pending/",previous_order_pending),
    path("items_in_order/<str:uid>/",items_in_order),
    
    path('get_resturent_by_food_cat/<str:cat>', get_resturent_by_food_cat),
    
    path('promo_code_price', promo_code_price),
    path('add_rating', add_rating),
    path('get_veg_noveg', get_veg_noveg),

    path("search_food/",search_food),
    path("search_product/",search_product),
    path("user_profile/",user_profile),
    path("order_placed_by_address_cod",order_placed_by_address_cod),
    # path("create_order",create_order),
    path("order_placed_by_address",order_placed_by_address),
    path("items_exists_in_cart/<str:uid>",items_exists_in_cart),

  #  path('login_to_pay/<str:code>', login_to_pay),
    path('success/<str:payment_id>', success),

    path("resrturent_banner",resrturent_banner),
    path("donate_for_cause",donate_for_cause),
    path("resturent_list_by_zipcode/<str:zipcode>",resturent_list_by_zipcode),
    path("add_shipping_address",add_shipping_address),
    path("view_shipping_address",view_shipping_address),
    path("delete_shipping_address/<int:pk>",delete_shipping_address),
    path("resturent_rating",resturent_rating),
    path("promo_code_list",promo_code_list),
    path("list_special_foog_category",list_special_foog_category),
    path("list_special_foog_category_by_name/<str:name>",list_special_foog_category_by_name),
    path("list_speacial_dish",list_speacial_dish),
    path("list_speacial_dish_food/str:name>",list_speacial_dish_food),
    path("store_list_by_zipcode/<str:zipcode>",store_list_by_zipcode),
    path("view_resturent_spotlight",view_resturent_spotlight),
    path("view_store_spotlight",view_store_spotlight),
    path("view_food_spotlight",view_food_spotlight),
    path("view_product_spotlight/",view_product_spotlight),
    path("all_name_special_resturent",all_name_special_resturent),
    path("special_resturent_name/<str:name>",special_resturent_name),
    path("get_veg_noveg_by_resturent",get_veg_noveg_by_resturent),
    path("spotlight_product_category",spotlight_product_category),
    path("create_order",create_order),
    path("cancel_order",cancel_order),
    path("re_order",re_order),
    path("canceled_order",canceled_order),
    path('rate_emp',rate_emp),
    path('view_rating_for_delivery',view_rating_for_delivery),
    path('check_cart',check_cart),
#    path('check_cart_product',check_cart_product),
    path('empty_cart', empty_cart),
    path('logout',logout),
    path("spotlight_food_category",spotlight_food_category),
    path("remove_extra_item",remove_extra_item),
    path('check_wallet',check_wallet),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


