# Generated by Django 3.1.2 on 2020-12-31 12:35

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=' ', max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('opt', models.CharField(default='', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.CharField(default='', max_length=50)),
                ('shipping_city', models.CharField(default='noida', max_length=100)),
                ('shipping_state', models.CharField(default='Delhi', max_length=100)),
                ('shipping_zipcode', models.CharField(default='666666', max_length=10)),
                ('shipping_address', models.CharField(default='xyx', max_length=400)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('order_type', models.CharField(default='', max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('tip', models.IntegerField(default=0)),
                ('rest', models.CharField(default=' ', max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='shipping_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200)),
                ('city', models.CharField(default='noida', max_length=50)),
                ('state', models.CharField(default='Delhi', max_length=50)),
                ('zipcode', models.CharField(default='666666', max_length=10)),
                ('address', models.CharField(default='address', max_length=500)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_sub_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_order_item', models.CharField(default=' ', max_length=50)),
                ('cat_name', models.CharField(default='cat name', max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodordering.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_uid', models.CharField(default=' ', max_length=20)),
                ('item_type', models.CharField(default=' ', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('cost', models.IntegerField(default=0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodordering.order')),
            ],
        ),
        migrations.CreateModel(
            name='order_exra_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_order_item', models.CharField(default=' ', max_length=50)),
                ('cat_name', models.CharField(default='cat name', max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodordering.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('donate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cms.donate')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodordering.order')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=20)),
                ('mobile', models.CharField(default='9999999999', max_length=20)),
                ('billing_city', models.CharField(default='noida', max_length=100)),
                ('billing_state', models.CharField(default='Delhi', max_length=100)),
                ('billing_zipcode', models.CharField(default='666666', max_length=10)),
                ('billing_address', models.CharField(default='xyx', max_length=400)),
                ('image', models.ImageField(blank=True, default='product/linux_2-wallpaper-1366x768.jpg', null=True, upload_to='customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cart_sub_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_cart_item', models.CharField(default=' ', max_length=50)),
                ('cat_name', models.CharField(default='cat name', max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cart_exra_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_cart_item', models.CharField(default=' ', max_length=50)),
                ('cat_name', models.CharField(default='cat name', max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_uid', models.CharField(default=' ', max_length=20)),
                ('item_type', models.CharField(default=' ', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
