from django.contrib import admin
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("logout_view/",logout_view,name="logout_view"),
    path("",login_view,name="login_view"),
    path("add_cms_employee/",add_cms_employee,name="add_cms_employee"),
    path("add_store_category/",add_store_category,name="add_store_category"),
    path("index/",index,name="index"),
    path("view_store_category/",view_store_category,name="view_store_category"),
    path("update_store_category/<int:pk>",update_store_category,name="update_store_category"),
    path("add_store/",add_store,name="add_store"),
    path("view_store/",view_store,name="view_store"),
    path("update_store/<str:uid>",update_store,name="update_store"),
    path("delete_store/<str:uid>",delete_store,name="delete_store"),
    path("add_store_product_category/",add_store_product_category,name="add_store_product_category"),
    path("view_store_product_category/",view_store_product_category,name="view_store_product_category"),
    path("update_store_product_category/<str:name>",update_store_product_category,name="update_store_product_category"),
    path("view_store_product/<str:uid>",view_store_product,name="view_store_product"),
    path("add_store_product/<str:uid>/",add_store_product,name="add_store_product"),
    path("update_store_product/<str:uid>&<str:st_uid>/",update_store_product,name="update_store_product"),
    path("delete_product/<str:uid>&<str:st_uid>/",delete_product,name="delete_product"),
    path("add_resturent_category/",add_resturent_category,name="add_resturent_category"),
    path("view_resturent_category/",view_resturent_category,name="view_resturent_category"),
    path("update_resturent_category/<int:pk>/",update_resturent_category,name="update_resturent_category"),
    path("view_resturent/",view_resturent,name="view_resturent"),
    path("add_resturent/",add_resturent,name="add_resturent"),
    path("update_resturent/<str:uid>/",update_resturent,name="update_resturent"),
    path("delete_resturent/<str:uid>/",delete_resturent,name="delete_resturent"),
    path("view_food_category/",view_food_category,name="view_food_category"),
    path("add_food_category/",add_food_category,name="add_food_category"),
    path("update_food_category/<int:pk>/",update_food_category,name="update_food_category"),
    path("view_food/<str:uid>/",view_food,name="view_food"),
    path("add_food/<str:uid>/",add_food,name="add_food"),
    path("update_food/<str:uid>/",update_food,name="update_food"),
    path("delete_food/<str:uid>/",delete_food,name="delete_food"),
    path("add_product_image/<str:uid>/",add_product_image,name="add_product_image"),
    path("view_product_image/<str:uid>/",view_product_image,name="view_product_image"),
    path("delete_product_image/<str:uid>&<int:pk>/",delete_product_image,name="delete_product_image"),
    path("view_product_specification/<str:uid>/",view_product_specification,name="view_product_specification"),
    path("delete_product_specification/<str:uid>&<int:pk>/",delete_product_specification,name="delete_product_specification"),
    path("add_product_specification/<str:uid>/",add_product_specification,name="add_product_specification"),
    path("view_food_image/<str:uid>/",view_food_image,name="view_food_image"),
    path("add_food_image/<str:uid>/",add_food_image,name="add_food_image"),
    path("delete_food_image/<str:uid>&<int:pk>/",delete_food_image,name="delete_food_image"),
    path("add_food_specification/<str:uid>/",add_food_specification,name="add_food_specification"),
    path("view_food_specification/<str:uid>/",view_food_specification,name="view_food_specification"),
    path("delete_food_specification/<str:uid>&<int:pk>/",delete_food_specification,name="delete_food_specification"),
    path("manage_customer/",manage_customer,name="manage_customer"),
    path("single_customer_panel/<str:uid>/",single_customer_panel),
    path("product_for_order/<str:c_uid>/",product_for_order),
    path("add_to_cart_for_product/<str:c_uid>&<str:uid>/",add_to_cart_for_product),
    path("single_product_for_cms/<str:c_uid>&<str:uid>/",single_product_for_cms),
    path("see_cart/<str:c_uid>/",see_cart),
    path("update_cart/<str:c_uid>&<str:uid>/",update_cart),
    # path("place_order_on_same_address/<str:c_uid>/",place_order_on_same_address),
    path("place_order_on_different_address/<str:c_uid>/",place_order_on_different_address),
    path("previous_order_complete/<str:c_uid>/",previous_order_complete),
    path("previous_order_pending/<str:c_uid>/",previous_order_pending),
    path("ordered_items/<str:o_uid>/",ordered_items),
    path("cancel_order/<str:o_uid>&<str:c_uid>/",cancel_order),
    path("cancel_order_pending/<str:c_uid>/",cancel_order_pending),
    path("delivery_details/",delivery_details),
    path("delivery_assigned/<str:uid>&<str:status>/",delivery_assigned),

    path('add_to_spotlight_store', add_to_spotlight_store),
    path('remove_from_spotlight_store/<int:pk>', remove_from_spotlight_store),
    path('add_to_spotlight_restaurant', add_to_spotlight_restaurant),
    path('remove_from_spotlight_restaurant/<int:pk>', remove_from_spotlight_restaurant),
    path("not_authorized/",not_authorized),
    path("single_product_details/<str:uid>/",single_product_details),
    path("add_delivery_employee/",add_delivery_employee),
    path("update_delivery_employee/<str:uid>/",update_delivery_employee),
    path("delete_promo_code/<int:pk>/",delete_promo_code),
    path("view_promo_code/",view_promo_code),
    path("add_promo_code/",add_promo_code),
    path("update_promo_code/<int:pk>/",update_promo_code),
    path('add_banner',add_banner,name="add_banner"),
    path('add_social_cause', add_social_cause),
    path('add_insplotlight_product', add_insplotlight_product),
    path('add_insplotlight_food', add_insplotlight_food),
    path('add_inspotlight_food_cat', add_inspotlight_food_cat),
    path('add_inspotlight_product_cat', add_inspotlight_product_cat),
    path("view_resturent_spotlight",view_resturent_spotlight),
    path('view_store_spotlight',view_store_spotlight),
    path("view_social_cause",view_social_cause),
    path("remove_social_cause/<int:pk>",remove_social_cause),
    path("add_social_cause",add_social_cause),
    path("remove_banner/<str:uid>",remove_banner),
    path("view_inspotlight_product_cat",view_inspotlight_product_cat),
    path("remove_inspotlight_product_cat/<int:pk>",remove_inspotlight_product_cat),
    path("view_inspotlight_food_cat",view_inspotlight_food_cat),
    path("remove_inspotlight_food_cat/<int:pk>",remove_inspotlight_food_cat),
    path("add_insplotlight_food",add_insplotlight_food),
    path("view_inspotlight_food",view_inspotlight_food),
    path("remove_inspotlight_food/<int:pk>",remove_inspotlight_food),
    path("view_inspotlight_product",view_inspotlight_product),
    path("remove_inspotlight_product",remove_inspotlight_product),
    path("add_special_resturent",add_special_resturent),
    path("view_special_resturent",view_special_resturent),
    path("delete_special_resturent/<int:pk>",delete_special_resturent),
    path("upload_store_csv",upload_store_csv),
    path("upload_resturent_csv",upload_resturent_csv),
    path("upload_product_csv",upload_product_csv),
    path("upload_food_csv",upload_food_csv),
    path("view_store_log",view_store_log),
    path("view_resturent_log",view_resturent_log)

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)